//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.Constants.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Constants.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully registered barber shop, we are working on approveing you barbershop. When your barbershop is approved you will receive an email..
        /// </summary>
        public static string BarberShopRegistrationSussesfuly {
            get {
                return ResourceManager.GetString("BarberShopRegistrationSussesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email..
        /// </summary>
        public static string EmailConfirmationSucceeded {
            get {
                return ResourceManager.GetString("EmailConfirmationSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset email sent successfully. Check your inbox..
        /// </summary>
        public static string EmailPasswordResetLinkSent {
            get {
                return ResourceManager.GetString("EmailPasswordResetLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when confirming the email..
        /// </summary>
        public static string ErrorConfirmingEmail {
            get {
                return ResourceManager.GetString("ErrorConfirmingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when creating the user..
        /// </summary>
        public static string ErrorCreatingUser {
            get {
                return ResourceManager.GetString("ErrorCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when reseting your password..
        /// </summary>
        public static string ErrorResetingPassword {
            get {
                return ResourceManager.GetString("ErrorResetingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending the email..
        /// </summary>
        public static string ErrorSendingEmail {
            get {
                return ResourceManager.GetString("ErrorSendingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please try again later..
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City dose not exists..
        /// </summary>
        public static string InvalidCity {
            get {
                return ResourceManager.GetString("InvalidCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District dose not exists..
        /// </summary>
        public static string InvalidDistrict {
            get {
                return ResourceManager.GetString("InvalidDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication, please log in again..
        /// </summary>
        public static string InvalidJwtToken {
            get {
                return ResourceManager.GetString("InvalidJwtToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid information..
        /// </summary>
        public static string InvalidValidationObject {
            get {
                return ResourceManager.GetString("InvalidValidationObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loged in..
        /// </summary>
        public static string LogInSussesfuly {
            get {
                return ResourceManager.GetString("LogInSussesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully loged out..
        /// </summary>
        public static string LogOutSussesfuly {
            get {
                return ResourceManager.GetString("LogOutSussesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing city import json file..
        /// </summary>
        public static string MissingCityJsonFile {
            get {
                return ResourceManager.GetString("MissingCityJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing neighborhoods import json file..
        /// </summary>
        public static string MissingNeighborhoodJsonFile {
            get {
                return ResourceManager.GetString("MissingNeighborhoodJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string ModelStateValidationErrorMessage {
            get {
                return ResourceManager.GetString("ModelStateValidationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active Http context..
        /// </summary>
        public static string NoActiveHttpContext {
            get {
                return ResourceManager.GetString("NoActiveHttpContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset successfully, please log in..
        /// </summary>
        public static string PasswordResetSussesfuly {
            get {
                return ResourceManager.GetString("PasswordResetSussesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route template is not congigured..
        /// </summary>
        public static string RouteTemplateNotConfigured {
            get {
                return ResourceManager.GetString("RouteTemplateNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user..
        /// </summary>
        public static string UserDoesNotExist {
            get {
                return ResourceManager.GetString("UserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists..
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked out, please try again later..
        /// </summary>
        public static string UserIsLockedOut {
            get {
                return ResourceManager.GetString("UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been registered..
        /// </summary>
        public static string UserRegistrationSussesfuly {
            get {
                return ResourceManager.GetString("UserRegistrationSussesfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists..
        /// </summary>
        public static string UserWithEmailDoesNotExist {
            get {
                return ResourceManager.GetString("UserWithEmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong email or password..
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
